name: LNMservices Django build and push image workflow

env:
  DJANGO_VERSION: 0.0.1

on:
  push:
    branches: [ "main" ]
    paths:
      - "."
  workflow_dispatch:

jobs:
  release_django:
    runs-on: github-actions
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - id: buildx-context
        run: |
          docker context create builder

      - id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: builder

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{env.ST3_DJANGO_REPO}}:${{env.DJANGO_VERSION}},${{env.ST3_DJANGO_REPO}}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max