name: LNMservices Django build and push image workflow

env:
  DJANGO_VERSION: 0.0.1
  ST3_DJANGO_REPO: us-central1-docker.pkg.dev/tanay-lnmservices/lnm-services  # Set your Docker repository name here

on:
  push:
    branches: [ "main" ]
    paths:
      - "**"
  workflow_dispatch:

jobs:
  release_django:
    runs-on: ubuntu-latest  # Specify the runner environment
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}



      - id: buildx-context
        run: |
          docker context create builder

      - id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: builder

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{env.ST3_DJANGO_REPO}}/lnmservices:${{env.DJANGO_VERSION}} # must be in lowercase
          cache-from: type=gha
          cache-to: type=gha,mode=max
